# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_historicalcity_historicalstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='city',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='historicalcity',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='historicalcity',
            name='update_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='update_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='state',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
