# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    replaces = [('bank', '0001_initial'), ('bank', '0002_auto_20180104_1554'), ('bank', '0003_auto_20180106_0851'), ('bank', '0004_auto_20180109_0816'), ('bank', '0005_file'), ('bank', '0006_auto_20180118_1541'), ('bank', '0007_auto_20180121_1122'), ('bank', '0008_auto_20180121_1202'), ('bank', '0009_auto_20180122_2139'), ('bank', '0010_personoffice'), ('bank', '0011_auto_20180125_1636'), ('bank', '0012_auto_20180126_1015'), ('bank', '0013_auto_20180129_1502'), ('bank', '0014_auto_20180129_1507'), ('bank', '0015_fileoffice'), ('bank', '0016_auto_20180129_2118'), ('bank', '0017_auto_20180130_0858'), ('bank', '0018_auto_20180130_0902'), ('bank', '0019_auto_20180130_0904'), ('bank', '0020_auto_20180130_0904'), ('bank', '0021_auto_20180130_0913'), ('bank', '0022_auto_20180130_0917'), ('bank', '0023_auto_20180203_2001'), ('bank', '0024_auto_20180209_1603'), ('bank', '0025_auto_20180213_0940'), ('bank', '0026_auto_20180213_0953'), ('bank', '0027_smstype'), ('bank', '0028_smstype_enable'), ('bank', '0029_auto_20180221_0812'), ('bank', '0030_branch_code'), ('bank', '0031_fileoffice_description'), ('bank', '0032_auto_20180304_0952'), ('bank', '0033_auto_20180304_0952'), ('bank', '0034_auto_20180304_0953'), ('bank', '0035_managementareas_status'), ('bank', '0036_auto_20180304_2052'), ('bank', '0037_auto_20180304_2054'), ('bank', '0038_auto_20180304_2131')]

    dependencies = [
        ('states', '0002_city_state'),
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=100, verbose_name='bank name')),
            ],
            options={
                'verbose_name': 'bank',
                'verbose_name_plural': 'banks',
                'db_table': 'banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('address', models.TextField(default=None, null=True, verbose_name='address')),
                ('postal_code', models.CharField(default=None, max_length=20, null=True, verbose_name='postal code')),
                ('name', models.CharField(max_length=100, verbose_name='branch name')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branch',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManagementAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('address', models.TextField(default=None, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(default=None, max_length=20, null=True, verbose_name='کد/شناسه')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرپرستی')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='bank.Bank', verbose_name='بانک')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_state', to='states.State', verbose_name='استان')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'bank',
                'verbose_name_plural': 'banks',
                'db_table': 'areas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='bank.ManagementAreas', verbose_name='area'),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='states.City', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='bank name'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('file_code', models.CharField(max_length=200, unique=True, verbose_name='کد پرونده')),
                ('contract_code', models.CharField(max_length=200, unique=True, verbose_name='شماره قرارداد')),
                ('main_deposit', models.PositiveIntegerField(default=100, verbose_name='اصل مبلغ بدهی')),
                ('cost_proceeding', models.PositiveIntegerField(default=100, verbose_name='هزینه دادرسی')),
                ('status', models.CharField(choices=[('سررسید گذشته', 'سر رسید گذشته'), ('معوق', 'معوق'), ('مشکوک الوصول', 'مشکوک الوصول')], default='مشکوک', max_length=20, verbose_name='وضعیت')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Branch', verbose_name='شعبه')),
                ('file_type', models.CharField(choices=[('جعاله', 'جعاله'), ('اعتباری خرید کالا', 'اعتباری خرید کالا'), ('خرید خودرو', 'خرید خودرو')], default='جعاله', max_length=50, verbose_name='نوع قرارداد')),
                ('nc_deposit', models.PositiveIntegerField(default=100, verbose_name='وجه التزام')),
                ('persian_date_refrence', models.CharField(default=None, max_length=10, null=True, verbose_name='تاریخ ارجاع')),
                ('persian_normal_date_refrence', models.CharField(default=None, max_length=10, null=True, verbose_name='تاریخ ارجاع')),
                ('so_deposit', models.PositiveIntegerField(default=100, verbose_name='سود')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'db_table': 'files',
                'ordering': ['file_code'],
            },
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('image_upload', models.ImageField(null=True, upload_to='document', verbose_name='تصویر')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
                ('assurance_type', models.CharField(choices=[('سفته', 'سفته'), ('چک', 'چک'), ('سند ملکی', 'سند ملکی'), ('سند در رهن', 'سند در رهن')], default='سفته', max_length=50, verbose_name='نو وثیقه')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'assurance',
                'verbose_name_plural': 'assurances',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('first_name', models.CharField(max_length=200, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last_name')),
                ('father_name', models.CharField(max_length=200, verbose_name='father_name')),
                ('national_code', models.CharField(max_length=20, verbose_name='national code')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=20, verbose_name='gender')),
            ],
            options={
                'verbose_name_plural': 'persons',
                'db_table': 'persons',
                'verbose_name': 'person',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('relation_type', models.CharField(choices=[('مدیون', 'مدیون'), ('ضامن', 'ضامن'), ('منفرقه', 'متفرقه')], default='مدیون', max_length=10, verbose_name='ارتباط')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_persons', to='bank.File', verbose_name='پرونده')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_persons', to='bank.Person', verbose_name='شخص')),
            ],
            options={
                'verbose_name_plural': 'person_files',
                'verbose_name': 'person_file',
                'db_table': 'person_humans',
            },
        ),
        migrations.AlterField(
            model_name='branch',
            name='postal_code',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='کد شعبه'),
        ),
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.ManyToManyField(related_name='persons', through='bank.PersonHuman', to='bank.File', verbose_name='شخص'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='bank.PersonFile', verbose_name='per'),
        ),
        migrations.AlterModelTable(
            name='assurance',
            table='assurances',
        ),
        migrations.AlterModelTable(
            name='personfile',
            table='person_files',
        ),
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(max_length=200, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=20, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد ملی'),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('register_number', models.PositiveIntegerField(unique=True, verbose_name='شماره ثبت')),
                ('address', models.TextField(default=None, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(default=None, max_length=20, null=True, verbose_name='کد پستی')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.City', verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'person_office',
                'verbose_name_plural': 'person_offices',
                'db_table': 'person_offices',
                'ordering': ['register_number'],
            },
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(default=None, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterUniqueTogether(
            name='personfile',
            unique_together=set([('file', 'person')]),
        ),
        migrations.CreateModel(
            name='FileOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('relation_type', models.CharField(choices=[('مدیون', 'مدیون'), ('ضامن', 'ضامن'), ('منفرقه', 'متفرقه')], default='مدیون', max_length=10, verbose_name='ارتباط')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_office', to='bank.File', verbose_name='پرونده')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_office', to='bank.Office', verbose_name='شرکت')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
            ],
            options={
                'db_table': 'file_offices',
                'verbose_name_plural': 'file_offices',
                'verbose_name': 'file_office',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fileoffice',
            unique_together=set([('file', 'office')]),
        ),
        migrations.RemoveField(
            model_name='assurance',
            name='person',
        ),
        migrations.AddField(
            model_name='assurance',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='bank.File', verbose_name='پرونده'),
        ),
        migrations.AlterField(
            model_name='assurance',
            name='assurance_type',
            field=models.CharField(choices=[('سفته', 'سفته'), ('چک', 'چک'), ('سند ملکی', 'سند ملکی'), ('سند در رهن', 'سند در رهن')], default='سفته', max_length=50, verbose_name='نوع وثیقه'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='assurance_number',
            field=models.CharField(max_length=200, null=True, verbose_name='شماره سند'),
        ),
        migrations.AlterUniqueTogether(
            name='assurance',
            unique_together=set([('file', 'assurance_type', 'assurance_number')]),
        ),
        migrations.AlterField(
            model_name='assurance',
            name='assurance_number',
            field=models.CharField(max_length=200, verbose_name='شماره سند'),
        ),
        migrations.AlterField(
            model_name='assurance',
            name='assurance_number',
            field=models.CharField(default=0, max_length=200, verbose_name='شماره سند'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='assurance_date',
            field=models.CharField(default='', max_length=200, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='assurance_value',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=20, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='assurance',
            name='image_upload',
            field=models.FileField(null=True, upload_to='document', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='file',
            name='persian_date_refrence',
            field=django_jalali.db.models.jDateField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='persian_date_refrence',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='تاریخ ارجاع'),
        ),
        migrations.CreateModel(
            name='SmsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('subject', models.CharField(max_length=50, unique=True, verbose_name='موضوع پیامک')),
                ('detail', models.TextField(verbose_name='مشروح پیامک')),
                ('enable', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name_plural': 'sms_types',
                'verbose_name': 'sms_type',
                'db_table': 'sms_types',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=100, null=True, verbose_name='کد شعبه'),
        ),
        migrations.AlterField(
            model_name='office',
            name='postal_code',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='کد/شناسه'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام شعبه'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='bank.ManagementAreas', verbose_name='سرپرستی'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='states.City', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='file',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bank.Branch', verbose_name='شعبه'),
        ),
    ]
