# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0002_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('image_upload', models.FileField(null=True, upload_to='document', verbose_name='تصویر')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
                ('assurance_type', models.CharField(choices=[('سفته', 'سفته'), ('چک', 'چک'), ('سند ملکی', 'سند ملکی'), ('سند در رهن', 'سند در رهن')], default='سفته', max_length=50, verbose_name='نوع وثیقه')),
                ('assurance_number', models.CharField(default=0, max_length=200, verbose_name='شماره سند')),
                ('assurance_date', models.CharField(default='', max_length=200, verbose_name='تاریخ')),
                ('assurance_value', models.PositiveIntegerField(default=0, verbose_name='مبلغ')),
            ],
            options={
                'db_table': 'assurances',
                'verbose_name': 'assurance',
                'verbose_name_plural': 'assurances',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='bank name')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'banks',
                'verbose_name': 'bank',
                'verbose_name_plural': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('address', models.TextField(default=None, null=True, verbose_name='آدرس')),
                ('name', models.CharField(max_length=100, verbose_name='نام شعبه')),
                ('code', models.CharField(max_length=100, null=True, verbose_name='کد شعبه')),
                ('postal_code', models.CharField(default=None, max_length=20, null=True, verbose_name='کد شعبه')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'branches',
                'verbose_name': 'branch',
                'verbose_name_plural': 'branch',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('file_code', models.CharField(max_length=200, unique=True, verbose_name='کد پرونده')),
                ('contract_code', models.CharField(max_length=200, unique=True, verbose_name='شماره قرارداد')),
                ('main_deposit', models.PositiveIntegerField(default=100, verbose_name='اصل مبلغ بدهی')),
                ('nc_deposit', models.PositiveIntegerField(default=100, verbose_name='وجه التزام')),
                ('so_deposit', models.PositiveIntegerField(default=100, verbose_name='سود')),
                ('cost_proceeding', models.PositiveIntegerField(default=100, verbose_name='هزینه دادرسی')),
                ('persian_date_refrence', models.CharField(default=None, max_length=10, null=True, verbose_name='تاریخ ارجاع')),
                ('persian_normal_date_refrence', models.CharField(default=None, max_length=10, null=True, verbose_name='تاریخ ارجاع')),
                ('status', models.CharField(choices=[('سررسید گذشته', 'سر رسید گذشته'), ('معوق', 'معوق'), ('مشکوک الوصول', 'مشکوک الوصول')], default='مشکوک', max_length=20, verbose_name='وضعیت')),
                ('file_type', models.CharField(choices=[('جعاله', 'جعاله'), ('اعتباری خرید کالا', 'اعتباری خرید کالا'), ('خرید خودرو', 'خرید خودرو')], default='جعاله', max_length=50, verbose_name='نوع قرارداد')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bank.Branch', verbose_name='شعبه')),
            ],
            options={
                'ordering': ['file_code'],
                'db_table': 'files',
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.CreateModel(
            name='FileOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('relation_type', models.CharField(choices=[('مدیون', 'مدیون'), ('ضامن', 'ضامن'), ('منفرقه', 'متفرقه')], default='مدیون', max_length=10, verbose_name='ارتباط')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_office', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'db_table': 'file_offices',
                'verbose_name': 'file_office',
                'verbose_name_plural': 'file_offices',
            },
        ),
        migrations.CreateModel(
            name='ManagementAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('address', models.TextField(default=None, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(default=None, max_length=20, null=True, verbose_name='کد/شناسه')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرپرستی')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='bank.Bank', verbose_name='بانک')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_state', to='states.State', verbose_name='استان')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'areas',
                'verbose_name': 'bank',
                'verbose_name_plural': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('address', models.TextField(default=None, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(default=None, max_length=20, null=True, verbose_name='کد/شناسه')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('register_number', models.PositiveIntegerField(unique=True, verbose_name='شماره ثبت')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.City', verbose_name='نام شهر')),
            ],
            options={
                'ordering': ['register_number'],
                'db_table': 'person_offices',
                'verbose_name': 'person_office',
                'verbose_name_plural': 'person_offices',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=200, null=True, verbose_name='نام پدر')),
                ('national_code', models.CharField(max_length=20, null=True, unique=True, verbose_name='کد ملی')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=20, null=True, verbose_name='جنسیت')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'db_table': 'persons',
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.CreateModel(
            name='PersonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('relation_type', models.CharField(choices=[('مدیون', 'مدیون'), ('ضامن', 'ضامن'), ('منفرقه', 'متفرقه')], default='مدیون', max_length=10, verbose_name='ارتباط')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_persons', to='bank.File', verbose_name='پرونده')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_persons', to='bank.Person', verbose_name='شخص')),
            ],
            options={
                'db_table': 'person_files',
                'verbose_name': 'person_file',
                'verbose_name_plural': 'person_files',
            },
        ),
        migrations.CreateModel(
            name='SmsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('subject', models.CharField(max_length=50, unique=True, verbose_name='موضوع پیامک')),
                ('detail', models.TextField(verbose_name='مشروح پیامک')),
                ('enable', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'db_table': 'sms_types',
                'verbose_name': 'sms_type',
                'verbose_name_plural': 'sms_types',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.ManyToManyField(related_name='persons', through='bank.PersonFile', to='bank.File', verbose_name='شخص'),
        ),
        migrations.AddField(
            model_name='fileoffice',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_office', to='bank.Office', verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='branch',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='bank.ManagementAreas', verbose_name='سرپرستی'),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='states.City', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='bank.File', verbose_name='پرونده'),
        ),
        migrations.AlterUniqueTogether(
            name='personfile',
            unique_together=set([('file', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='fileoffice',
            unique_together=set([('file', 'office')]),
        ),
        migrations.AlterUniqueTogether(
            name='assurance',
            unique_together=set([('file', 'assurance_type', 'assurance_number')]),
        ),
    ]
