# Generated by Django 2.0 on 2017-12-29 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=100, verbose_name='bank name')),
            ],
            options={
                'verbose_name': 'bank',
                'verbose_name_plural': 'banks',
                'db_table': 'banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('address', models.TextField(default=None, null=True, verbose_name='address')),
                ('postal_code', models.CharField(default=None, max_length=20, null=True, verbose_name='postal code')),
                ('name', models.CharField(max_length=100, verbose_name='branch name')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branch',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManagementAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('address', models.TextField(default=None, null=True, verbose_name='address')),
                ('postal_code', models.CharField(default=None, max_length=20, null=True, verbose_name='postal code')),
                ('name', models.CharField(max_length=100, verbose_name='bank name')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='bank.Bank', verbose_name='bank')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_state', to='states.State', verbose_name='state')),
            ],
            options={
                'verbose_name': 'bank',
                'verbose_name_plural': 'banks',
                'db_table': 'areas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='bank.ManagementAreas', verbose_name='branches'),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='states.City', verbose_name='city'),
        ),
    ]
