# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='bank name'),
        ),
    ]
