# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='contract_code',
            field=models.CharField(max_length=200, null=True, verbose_name='شماره قرارداد'),
        ),
    ]
