# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20180104_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementareas',
            name='name',
            field=models.CharField(max_length=100, verbose_name='area name'),
        ),
    ]
