# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20180309_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='states',
            field=models.CharField(choices=[('جعاله', 'جعاله'), ('اعتباری خرید کالا', 'اعتباری خرید کالا'), ('خرید خودرو', 'خرید خودرو')], default='در حال پیگیری', max_length=50, verbose_name='وضعیت'),
        ),
    ]
