# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20180106_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='bank.ManagementAreas', verbose_name='area'),
        ),
    ]
