# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_file_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='states',
            field=models.CharField(choices=[('در حال پیگیری', 'در حال پیگیری'), ('عودت', 'عودت'), ('تسویه حساب', 'تسویه حساب')], default='در حال پیگیری', max_length=50, verbose_name='وضعیت'),
        ),
    ]
