# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20180109_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('file_code', models.CharField(max_length=200, verbose_name='کد پرونده')),
                ('contract_code', models.CharField(max_length=200, verbose_name='شماره قرارداد')),
                ('main_deposit', models.PositiveIntegerField(default=100, verbose_name='اصل مبلغ بدهی')),
                ('end_deposit', models.PositiveIntegerField(default=100, verbose_name='میزان خواسته')),
                ('cost_proceeding', models.PositiveIntegerField(default=100, verbose_name='هزینه دادرسی')),
                ('status', models.CharField(choices=[('سررسید گذشته', 'سر رسید گذشته'), ('معوق', 'معوق'), ('مشکوک الوصول', 'مشکوک الوصول')], default='مشکوک', max_length=20, verbose_name='وضعیت')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Branch', verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'db_table': 'files',
                'ordering': ['file_code'],
            },
        ),
    ]
