# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('image_upload', models.ImageField(null=True, upload_to='document', verbose_name='تصویر')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('first_name', models.CharField(max_length=200, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last_name')),
                ('father_name', models.CharField(max_length=200, verbose_name='father_name')),
                ('national_code', models.CharField(max_length=20, verbose_name='national code')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=20, verbose_name='gender')),
            ],
            options={
                'verbose_name_plural': 'persons',
                'db_table': 'persons',
                'verbose_name': 'person',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonHuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('relation_type', models.CharField(choices=[('مدیون', 'مدیون'), ('ضامن', 'ضامن'), ('منفرقه', 'متفرقه')], default='مدیون', max_length=10, verbose_name='ارتباط')),
            ],
            options={
                'verbose_name_plural': 'person_humans',
                'verbose_name': 'person_human',
                'db_table': 'person_humans',
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='end_deposit',
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('جعاله', 'جعاله'), ('اعتباری خرید کالا', 'اعتباری خرید کالا'), ('خرید خودرو', 'خرید خودرو')], default='جعاله', max_length=50, verbose_name='نوع قرارداد'),
        ),
        migrations.AddField(
            model_name='file',
            name='nc_deposit',
            field=models.PositiveIntegerField(default=100, verbose_name='وجه التزام'),
        ),
        migrations.AddField(
            model_name='file',
            name='persian_date_refrence',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='تاریخ ارجاع'),
        ),
        migrations.AddField(
            model_name='file',
            name='persian_normal_date_refrence',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='تاریخ ارجاع'),
        ),
        migrations.AddField(
            model_name='file',
            name='so_deposit',
            field=models.PositiveIntegerField(default=100, verbose_name='سود'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='postal_code',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='کد شعبه'),
        ),
        migrations.AlterField(
            model_name='file',
            name='contract_code',
            field=models.CharField(max_length=200, unique=True, verbose_name='شماره قرارداد'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_code',
            field=models.CharField(max_length=200, unique=True, verbose_name='کد پرونده'),
        ),
        migrations.AddField(
            model_name='personhuman',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_persons', to='bank.File', verbose_name='پرونده'),
        ),
        migrations.AddField(
            model_name='personhuman',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_persons', to='bank.Person', verbose_name='شخص'),
        ),
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.ManyToManyField(related_name='persons', through='bank.PersonHuman', to='bank.File', verbose_name='شخص'),
        ),
    ]
