# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_file_persian_date_refrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='persian_normal_date_refrence',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='تاریخ ارجاع'),
        ),
    ]
