# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20180118_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonHuman',
            new_name='PersonFile',
        ),
    ]
