# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_historicalassurance_historicalbank_historicalbranch_historicalfile_historicalfileoffice_historicalfi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='cost_proceeding',
            field=models.BigIntegerField(default=100, verbose_name='هزینه دادرسی'),
        ),
        migrations.AlterField(
            model_name='file',
            name='main_deposit',
            field=models.BigIntegerField(default=100, verbose_name='اصل مبلغ بدهی'),
        ),
        migrations.AlterField(
            model_name='file',
            name='nc_deposit',
            field=models.BigIntegerField(default=100, verbose_name='وجه التزام'),
        ),
        migrations.AlterField(
            model_name='file',
            name='so_deposit',
            field=models.BigIntegerField(default=100, verbose_name='سود'),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='cost_proceeding',
            field=models.BigIntegerField(default=100, verbose_name='هزینه دادرسی'),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='main_deposit',
            field=models.BigIntegerField(default=100, verbose_name='اصل مبلغ بدهی'),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='nc_deposit',
            field=models.BigIntegerField(default=100, verbose_name='وجه التزام'),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='so_deposit',
            field=models.BigIntegerField(default=100, verbose_name='سود'),
        ),
    ]
