# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20180121_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assurance',
            options={'verbose_name': 'assurance', 'verbose_name_plural': 'assurances'},
        ),
        migrations.AlterModelOptions(
            name='personfile',
            options={'verbose_name': 'person_file', 'verbose_name_plural': 'person_files'},
        ),
        migrations.AddField(
            model_name='assurance',
            name='assurance_type',
            field=models.CharField(choices=[('سفته', 'سفته'), ('چک', 'چک'), ('سند ملکی', 'سند ملکی'), ('سند در رهن', 'سند در رهن')], default='سفته', max_length=50, verbose_name='نو وثیقه'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='bank.PersonFile', verbose_name='per'),
        ),
        migrations.AlterModelTable(
            name='assurance',
            table='assurances',
        ),
        migrations.AlterModelTable(
            name='personfile',
            table='person_files',
        ),
    ]
