# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20180313_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloffice',
            name='register_number',
            field=models.PositiveIntegerField(null=True, verbose_name='شماره ثبت'),
        ),
        migrations.AlterField(
            model_name='office',
            name='register_number',
            field=models.PositiveIntegerField(null=True, verbose_name='شماره ثبت'),
        ),
    ]
