# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20180313_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloffice',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام شرکت'),
        ),
    ]
