# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20180122_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('register_number', models.PositiveIntegerField(unique=True, verbose_name='شماره ثبت')),
            ],
            options={
                'verbose_name': 'person_office',
                'verbose_name_plural': 'person_offices',
                'db_table': 'person_offices',
                'ordering': ['register_number'],
            },
        ),
    ]
