# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20180313_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
