# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_personoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='personoffice',
            name='address',
            field=models.TextField(default=None, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='personoffice',
            name='postal_code',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='postal code'),
        ),
    ]
