# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20180313_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
