# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_city_state'),
        ('bank', '0011_auto_20180125_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='personoffice',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.City', verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(default=None, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='managementareas',
            name='address',
            field=models.TextField(default=None, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='managementareas',
            name='postal_code',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='personoffice',
            name='address',
            field=models.TextField(default=None, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='personoffice',
            name='postal_code',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='کد پستی'),
        ),
    ]
