# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20180313_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='assurance_type',
            field=models.CharField(choices=[('سند رهنی', 'سند رهنی'), ('سفته', 'سفته'), ('چک', 'چک'), ('قرارداد لازم الاجرا', 'قرارداد لازم الاجرا'), ('ضمانت نامه', 'ضمانت نامه'), ('کسر از حقوق', 'کسر از حقوق')], default='سفته', max_length=50, verbose_name='نوع وثیقه'),
        ),
        migrations.AlterField(
            model_name='historicalassurance',
            name='assurance_type',
            field=models.CharField(choices=[('سند رهنی', 'سند رهنی'), ('سفته', 'سفته'), ('چک', 'چک'), ('قرارداد لازم الاجرا', 'قرارداد لازم الاجرا'), ('ضمانت نامه', 'ضمانت نامه'), ('کسر از حقوق', 'کسر از حقوق')], default='سفته', max_length=50, verbose_name='نوع وثیقه'),
        ),
    ]
