# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20180126_1015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonOffice',
            new_name='Office',
        ),
    ]
