# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20180414_0112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assurance',
            unique_together=set([('file', 'assurance_type')]),
        ),
    ]
