# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20180414_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='national_code',
            field=models.CharField(max_length=20, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.CharField(max_length=20, null=True, verbose_name='کد ملی'),
        ),
    ]
