# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_auto_20180129_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personfile',
            unique_together=set([('file', 'person')]),
        ),
    ]
