# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_auto_20180422_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurance',
            name='assurance_number',
        ),
        migrations.RemoveField(
            model_name='assurance',
            name='assurance_value',
        ),
        migrations.RemoveField(
            model_name='historicalassurance',
            name='assurance_number',
        ),
        migrations.RemoveField(
            model_name='historicalassurance',
            name='assurance_value',
        ),
    ]
