# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_auto_20180129_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('relation_type', models.CharField(choices=[('مدیون', 'مدیون'), ('ضامن', 'ضامن'), ('منفرقه', 'متفرقه')], default='مدیون', max_length=10, verbose_name='ارتباط')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_office', to='bank.File', verbose_name='پرونده')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_office', to='bank.Office', verbose_name='شرکت')),
            ],
            options={
                'db_table': 'file_offices',
                'verbose_name_plural': 'file_offices',
                'verbose_name': 'file_office',
            },
        ),
    ]
