# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_auto_20180422_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name'], 'verbose_name': 'بانک', 'verbose_name_plural': 'بانک ها'},
        ),
        migrations.AlterModelOptions(
            name='historicalbank',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical بانک'},
        ),
    ]
