# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_fileoffice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fileoffice',
            unique_together=set([('file', 'office')]),
        ),
    ]
