# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_auto_20180423_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assurance',
            options={'verbose_name': 'وثیقه', 'verbose_name_plural': 'وثایق'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'شعبه', 'verbose_name_plural': 'شعبات'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['file_code'], 'verbose_name': 'پرونده', 'verbose_name_plural': 'پرونده ها'},
        ),
        migrations.AlterModelOptions(
            name='fileoffice',
            options={'verbose_name': 'فرد حقیقی پرونده', 'verbose_name_plural': 'افراد حقیقی پرونده'},
        ),
        migrations.AlterModelOptions(
            name='filetype',
            options={'verbose_name': 'نوع پرونده', 'verbose_name_plural': 'انواع پرونده'},
        ),
        migrations.AlterModelOptions(
            name='historicalassurance',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical وثیقه'},
        ),
        migrations.AlterModelOptions(
            name='historicalbranch',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical شعبه'},
        ),
        migrations.AlterModelOptions(
            name='historicalfile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical پرونده'},
        ),
        migrations.AlterModelOptions(
            name='historicalfileoffice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical فرد حقیقی پرونده'},
        ),
        migrations.AlterModelOptions(
            name='historicalfiletype',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical نوع پرونده'},
        ),
        migrations.AlterModelOptions(
            name='historicalmanagementareas',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical منطقه'},
        ),
        migrations.AlterModelOptions(
            name='historicaloffice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical شخص حقوقی'},
        ),
        migrations.AlterModelOptions(
            name='historicalperson',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical شخص حقیقی'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersonfile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical شخص حقیقی پرونده'},
        ),
        migrations.AlterModelOptions(
            name='historicalsmstype',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical نوع پیامک'},
        ),
        migrations.AlterModelOptions(
            name='managementareas',
            options={'ordering': ['name'], 'verbose_name': 'منطقه', 'verbose_name_plural': 'مناطق'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['register_number'], 'verbose_name': 'شخص حقوقی', 'verbose_name_plural': 'اشخاص حقیقی'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'شخص حقیقی', 'verbose_name_plural': 'اشخاص حقیقی'},
        ),
        migrations.AlterModelOptions(
            name='personfile',
            options={'verbose_name': 'شخص حقیقی پرونده', 'verbose_name_plural': 'اشخاص حقیقی پرونده'},
        ),
        migrations.AlterModelOptions(
            name='smstype',
            options={'verbose_name': 'نوع پیامک', 'verbose_name_plural': 'انواع پیامک'},
        ),
    ]
