# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_auto_20180417_0617'),
        ('bank', '0016_auto_20180423_2132'),
    ]

    operations = [
    ]
