# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_auto_20180130_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='assurance_number',
            field=models.CharField(max_length=200, null=True, verbose_name='شماره سند'),
        ),
        migrations.AlterUniqueTogether(
            name='assurance',
            unique_together=set([('file', 'assurance_type', 'assurance_number')]),
        ),
    ]
