# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_auto_20180130_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='assurance_number',
            field=models.CharField(max_length=200, verbose_name='شماره سند'),
        ),
    ]
