# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_auto_20180510_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallawyerfile',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='lawyerfile',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
