# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_auto_20180510_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowLawType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('type', models.CharField(max_length=100, verbose_name='نوع پیگیری')),
                ('enable', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پیگیری حقوقی',
                'verbose_name_plural': 'پیگیری های حقوقی',
                'db_table': 'follow_low_type',
            },
        ),
    ]
