# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_auto_20180130_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='assurance_date',
            field=models.CharField(default='', max_length=200, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='assurance_value',
            field=models.PositiveIntegerField(default=0, verbose_name='تاریخ'),
        ),
    ]
