# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_followlawtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره همراه'),
        ),
    ]
