# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_auto_20180130_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='assurance_value',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ'),
        ),
    ]
