# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_lawyer_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowInLowFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('enable', models.BooleanField(default=False, verbose_name='فعال')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'پیگیری حقوقی پرونده',
                'verbose_name_plural': 'پیگیری های حقوقی پرونده',
                'db_table': 'follow_low_file',
            },
        ),
        migrations.RemoveField(
            model_name='followlawtype',
            name='enable',
        ),
        migrations.AlterField(
            model_name='historicallawyerfile',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='lawyerfile',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='followinlowfile',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.FollowLawType', verbose_name='پیگیری'),
        ),
    ]
