# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_auto_20180130_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=20, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='کد ملی'),
        ),
    ]
