# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_auto_20180203_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='image_upload',
            field=models.FileField(null=True, upload_to='document', verbose_name='تصویر'),
        ),
    ]
