# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 09:40
from __future__ import unicode_literals

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_auto_20180209_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='persian_date_refrence',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
