# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_auto_20180531_1412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assurance',
            unique_together=set([]),
        ),
    ]
