# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_auto_20180604_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='assurance_number',
            field=models.CharField(default=0, max_length=200, verbose_name='شماره سند'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='assurance_value',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='historicalassurance',
            name='assurance_number',
            field=models.CharField(default=0, max_length=200, verbose_name='شماره سند'),
        ),
        migrations.AddField(
            model_name='historicalassurance',
            name='assurance_value',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ'),
        ),
    ]
