# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_auto_20180213_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='persian_date_refrence',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='تاریخ ارجاع'),
        ),
    ]
