# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_auto_20180213_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع پیامک')),
                ('detail', models.TextField(verbose_name='مشروح پیامک')),
            ],
            options={
                'verbose_name_plural': 'sms_types',
                'verbose_name': 'sms_type',
                'db_table': 'sms_types',
            },
        ),
    ]
