# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_auto_20180604_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='assurance_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره سند'),
        ),
        migrations.AlterField(
            model_name='assurance',
            name='assurance_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='historicalassurance',
            name='assurance_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره سند'),
        ),
        migrations.AlterField(
            model_name='historicalassurance',
            name='assurance_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ'),
        ),
    ]
