# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_auto_20180604_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_code',
            field=models.CharField(error_messages={'unique': 'شماره پرونده وارد شده تکراری می باشد لطفا شماره دیگری وارد نمایید.'}, max_length=200, unique=True, verbose_name='کد پرونده'),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='file_code',
            field=models.CharField(db_index=True, error_messages={'unique': 'شماره پرونده وارد شده تکراری می باشد لطفا شماره دیگری وارد نمایید.'}, max_length=200, verbose_name='کد پرونده'),
        ),
    ]
