# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0028_smstype_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstype',
            name='subject',
            field=models.CharField(max_length=50, unique=True, verbose_name='موضوع پیامک'),
        ),
    ]
