# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0029_auto_20180624_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assurance',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='historicalassurance',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات'),
        ),
    ]
