# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0029_auto_20180221_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=100, null=True, verbose_name='کد شعبه'),
        ),
    ]
