# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0030_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileoffice',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
    ]
