# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0031_fileoffice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementareas',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='bank.Bank', verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='managementareas',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام منطقه'),
        ),
        migrations.AlterField(
            model_name='managementareas',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_state', to='states.State', verbose_name='استان'),
        ),
    ]
