# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0032_auto_20180304_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementareas',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام سرپرستی'),
        ),
    ]
