# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0034_auto_20180304_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementareas',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
