# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0035_managementareas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام شعبه'),
        ),
    ]
