# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0036_auto_20180304_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='bank.ManagementAreas', verbose_name='سرپرستی'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='states.City', verbose_name='شهر'),
        ),
    ]
