# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0037_auto_20180304_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bank.Branch', verbose_name='شعبه'),
        ),
    ]
