# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('person_type', models.CharField(choices=[('مدیون', 'مدیون'), ('ضامن', 'ضامن'), ('متفرقه', 'متفرقه')], default='مدیون', max_length=10, verbose_name='مالک')),
                ('type', models.CharField(choices=[('ملکی', 'ملکی'), ('استیجاری', 'استیجاری'), ('رهنی', 'رهنی')], default='ملکی', max_length=10, verbose_name='نوع مالکیت')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'db_table': 'employee_addresses',
                'verbose_name': 'employee_address',
                'verbose_name_plural': 'employee_addresses',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('وثیقه', 'وثیقه'), ('ضمانی', 'ضمانی'), ('متفرقه', 'متفرقه')], default='وثیقه', max_length=10, verbose_name='نوع مالکیت')),
                ('image_upload', models.ImageField(null=True, upload_to='document', verbose_name='تصویر سند')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'db_table': 'document_file',
                'verbose_name': 'نوع وثایق',
                'verbose_name_plural': 'نوع وثایق',
            },
        ),
        migrations.CreateModel(
            name='EmployeeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('status', models.CharField(choices=[('enable', 'فعال'), ('disable', 'غیر فعال')], default='enable', max_length=50, verbose_name='وضعیت')),
                ('auth_status', models.CharField(choices=[('کارشناس', 'کارشناس'), ('وکیل', 'وکیل')], default='کارشناس', max_length=50, verbose_name='نوع تخصیص')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'db_table': 'employee_files',
                'verbose_name': 'تخصیص پرونده',
                'verbose_name_plural': 'تخصیص پرونده',
            },
        ),
        migrations.CreateModel(
            name='FileRecovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('recovery_type', models.CharField(choices=[('نقدی', 'نقدی'), ('چک', 'چک'), ('فروش رهنی', 'فروش رهنی')], default='نقدی', max_length=100, verbose_name='نوع وصولی')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='مبلغ وصولی')),
                ('value_code', models.CharField(default='0', max_length=200, verbose_name='شماره سند')),
                ('detail', models.TextField(verbose_name='شرح')),
                ('recovery_date', django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ')),
                ('created_at', django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ')),
                ('assurance_confirm', models.BooleanField(default=False, verbose_name='تاییدیه مالی')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'db_table': 'file_recoveries',
                'verbose_name': 'file_recovery',
                'verbose_name_plural': 'file_recoveries',
            },
        ),
        migrations.CreateModel(
            name='FileReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('detail', models.TextField(verbose_name='شرح')),
                ('persian_date', django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'db_table': 'file_reminders',
                'verbose_name': 'file_reminder',
                'verbose_name_plural': 'file_reminders',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('follow_up_type', models.CharField(choices=[('call', 'تماس تلفنی'), ('meeting', 'مذاکره حضوری')], default='call', max_length=20, verbose_name='نوع پیگیری')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'db_table': 'employee_file_folllow_ups',
                'verbose_name': 'employee_file_folllow_up',
                'verbose_name_plural': 'employee_file_folllow_ups',
            },
        ),
        migrations.CreateModel(
            name='PhoneFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='bank.File', verbose_name='پرونده')),
                ('phone_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='bank.PersonFile', verbose_name='نام شخص')),
            ],
            options={
                'db_table': 'employee_phones',
                'verbose_name': 'employee_phone',
                'verbose_name_plural': 'employee_phones',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=200, null=True, verbose_name='نام پدر')),
                ('national_code', models.CharField(max_length=20, null=True, unique=True, verbose_name='کد ملی')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=20, null=True, verbose_name='جنسیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='پروفایل')),
            ],
            options={
                'db_table': 'profiles',
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='SmsCaution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('status', models.CharField(choices=[('در صف ارسال', 'در صف ارسال'), ('ارسال شد', 'ارسال شد'), ('دریافت شد', 'دریافت شد'), ('خطا در زمان ارسال', 'خطا در زمان ارسال')], default='در صف ارسال', max_length=100, verbose_name='وضعیت')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_cautions', to='bank.File', verbose_name='پرونده')),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.PhoneFile', verbose_name='شماره تلفن')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_cautions', to='bank.SmsType', verbose_name='نوع پیامک')),
            ],
            options={
                'db_table': 'employee_file_sms_caution',
                'verbose_name': 'employee_file_sms_caution',
                'verbose_name_plural': 'employee_file_sms_caution',
            },
        ),
        migrations.AlterUniqueTogether(
            name='smscaution',
            unique_together=set([('mobile_number', 'file', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='phonefile',
            unique_together=set([('phone_number', 'file')]),
        ),
        migrations.AlterUniqueTogether(
            name='filerecovery',
            unique_together=set([('file', 'recovery_type', 'value_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeefile',
            unique_together=set([('file', 'employee')]),
        ),
        migrations.AlterUniqueTogether(
            name='documentfile',
            unique_together=set([('type', 'file', 'description')]),
        ),
        migrations.AlterUniqueTogether(
            name='addressfile',
            unique_together=set([('address', 'file')]),
        ),
    ]
