# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0022_auto_20180130_0917'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'verbose_name_plural': 'employee_files',
                'db_table': 'employee_files',
                'verbose_name': 'employee_file',
            },
        ),
    ]
