# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='status',
            field=models.CharField(choices=[('ENABLE', 'enable'), ('DISABLE', 'disable')], default='enable', max_length=50, verbose_name='وضعیت'),
        ),
    ]
