# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.CharField(choices=[('کارشناسی حقوق', 'کارشناسی حقوق'), ('کارشناسی ارشد حقوق', 'کارشناسی ارشد حقوق'), ('کارشناسی ارشد حقوق', 'کارشناسی ارشد حقوق'), ('کارشناسی الکترونیک', 'کارشناسی الکترونیک'), ('لیسانس مدیریت', 'لیسانس مدیریت'), ('لیسانس صنایع', 'لیسانس صنایع'), ('کارشناسی ارشدحقوق جزا', 'کارشناسی ارشدحقوق جزا'), ('مدیریت دولتی- مدیریت نیروی انسانی', 'مدیریت دولتی- مدیریت نیروی انسانی')], default='کارشناسی حقوق', max_length=200, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_post',
            field=models.CharField(choices=[('کارشناسی حقوق', 'کارشناسی حقوق'), ('کارشناسی ارشد حقوق', 'کارشناسی ارشد حقوق')], default='کارشناسی حقوق', max_length=200, verbose_name='سمت'),
        ),
    ]
