# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeefile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='status',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='enable', max_length=50, verbose_name='وضعیت'),
        ),
    ]
