# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefile',
            options={'permissions': (('employee_file', 'employee file permissions'),), 'verbose_name': 'تخصیص پرونده', 'verbose_name_plural': 'تخصیص پرونده'},
        ),
    ]
