# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20180309_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefile',
            options={'permissions': (('employee_file', 'employee file permissions'), ('employee_file_assign', 'assifgn file to employee')), 'verbose_name': 'تخصیص پرونده', 'verbose_name_plural': 'تخصیص پرونده'},
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={'permissions': (('create_follow', 'create followup for file'), ('update_follow', 'update followup for file'), ('read_follow', 'read followup for file')), 'verbose_name': 'employee_file_folllow_up', 'verbose_name_plural': 'employee_file_folllow_ups'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('edit_profile', 'edit profile'),), 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
