# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_auto_20180203_2001'),
        ('employee', '0006_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCaution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('caution_type', models.CharField(choices=[('caution1', 'اخطار اول'), ('caution2', 'اخطار دوم'), ('caution3', 'اخطار سوم')], default='caution1', max_length=20, verbose_name='نوع اخطار')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_cautions', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'employee_file_sms_caution',
                'verbose_name_plural': 'employee_file_sms_caution',
                'db_table': 'employee_file_sms_caution',
            },
        ),
    ]
