# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20180313_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeefile',
            options={'permissions': (('employee_file', 'employee file permissions'), ('employee_file_assign', 'assign file to employee')), 'verbose_name': 'تخصیص پرونده', 'verbose_name_plural': 'تخصیص پرونده'},
        ),
    ]
