# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 10:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_smscaution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscaution',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
