# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20180208_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscaution',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='توضیحات'),
        ),
    ]
