# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 05:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0008_auto_20180316_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('permission_type', models.CharField(choices=[('dashboard', 'داشبورد'), ('employee_file', 'پرونده های کارشناسان'), ('bank_new', 'ایجاد بانک'), ('bank_edit', 'ویرایش بانک'), ('bank_list', 'لیست بانک'), ('area_new', 'سرپرستی جدید'), ('area_edit', 'ویرایش سرپرستی'), ('area_list', 'لیست مناطق'), ('branch_new', 'شعبه جدید'), ('branch_edit', 'ویرایش شعبه'), ('branch_list', 'لیست شعب'), ('file_new', 'پرونده جدید'), ('file_edit', 'ویرایش پرونده'), ('file_list', 'لیست پرونده ها'), ('office_new', 'شخص حقوقی جدید'), ('office_edit', 'ویرایش شخص حقوقی'), ('office_list', 'لیست اشخاص حقوقی'), ('report_user', 'گزارش عملکرد کارشناسان'), ('report_bank', 'گزارش به تفکیک بانک'), ('role_access', 'تعیین سطح دسترسی')], default='dashboard', max_length=100, verbose_name='دسترسی')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'employee_permission',
                'verbose_name_plural': 'employee_permission',
                'db_table': 'employee_permission',
            },
        ),
        migrations.AlterUniqueTogether(
            name='employeepermission',
            unique_together=set([('permission_type', 'employee')]),
        ),
    ]
