# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20180316_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
