# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_auto_20180203_2001'),
        ('employee', '0010_phonefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonefile',
            name='person_type',
            field=models.CharField(choices=[('مدیون', 'مدیون'), ('ضامن', 'ضامن'), ('متفرقه', 'متفرقه')], default='مدیون', max_length=10, verbose_name='مالک'),
        ),
        migrations.AlterUniqueTogether(
            name='phonefile',
            unique_together=set([('phone_number', 'file')]),
        ),
    ]
