# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_auto_20180203_2001'),
        ('employee', '0011_auto_20180208_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('person_type', models.CharField(choices=[('مدیون', 'مدیون'), ('ضامن', 'ضامن'), ('متفرقه', 'متفرقه')], default='مدیون', max_length=10, verbose_name='مالک')),
                ('type', models.CharField(choices=[('ملکی', 'ملکی'), ('استیجاری', 'استیجاری'), ('رهنی', 'رهنی')], default='ملکی', max_length=10, verbose_name='نوع خط')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'db_table': 'employee_address',
                'verbose_name_plural': 'employee_addresses',
                'verbose_name': 'employee_addresses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='addressfile',
            unique_together=set([('address', 'file')]),
        ),
    ]
