# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20180208_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressfile',
            options={'verbose_name': 'employee_address', 'verbose_name_plural': 'employee_addresses'},
        ),
        migrations.AlterModelTable(
            name='addressfile',
            table='employee_addresses',
        ),
    ]
