# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 13:21
from __future__ import unicode_literals

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20180406_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='recovery_date',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ ارجاع'),
        ),
    ]
