# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employeefile_recovery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'mail',
                'db_table': 'mails',
                'verbose_name_plural': 'mails',
            },
        ),
    ]
