# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_auto_20180203_2001'),
        ('employee', '0014_auto_20180209_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('image_upload', models.ImageField(null=True, upload_to='document', verbose_name='تصویر')),
                ('description', models.TextField(default=None, null=True, verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('وثیقه', 'وثیقه'), ('ضمانی', 'ضمانی'), ('متفرقه', 'متفرقه')], default='وثیقه', max_length=10, verbose_name='نوع مالکیت')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'db_table': 'document_file',
                'verbose_name_plural': 'document_file',
                'verbose_name': 'document_file',
            },
        ),
        migrations.AlterUniqueTogether(
            name='documentfile',
            unique_together=set([('type', 'file', 'description')]),
        ),
    ]
