# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0014_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_messages', to=settings.AUTH_USER_MODEL, verbose_name='از')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='employee.Mail', verbose_name='نامه')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_messages', to=settings.AUTH_USER_MODEL, verbose_name='به')),
            ],
            options={
                'verbose_name_plural': 'mail_boxes',
                'verbose_name': 'mail_box',
                'db_table': 'mail_boxes',
            },
        ),
    ]
