# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20180209_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='image_upload',
            field=models.ImageField(null=True, upload_to='document/%y%m%d', verbose_name='تصویر سند'),
        ),
    ]
