# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20180409_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='type',
            field=models.CharField(choices=[('سند رهنی', 'سند رهنی'), ('سفته', 'سفته'), ('چک', 'چک'), ('قرارداد لازم الاجرا', 'قرارداد لازم الاجرا'), ('ضمانت نامه', 'ضمانت نامه'), ('کسر از حقوق', 'کسر از حقوق')], default='وثیقه', max_length=10, verbose_name='وثایق'),
        ),
    ]
