# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20180209_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='image_upload',
            field=models.ImageField(null=True, upload_to='document', verbose_name='تصویر سند'),
        ),
    ]
