# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20180414_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='type',
            field=models.CharField(choices=[('اسناد ضمه ای', 'اسناد ضمه ای'), ('قرارداد', 'قرارداد')], default='وثیقه', max_length=10, verbose_name='وثایق'),
        ),
    ]
