# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_auto_20180213_0953'),
        ('employee', '0018_auto_20180213_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('detail', models.TextField(verbose_name='شرح')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'file_reminder',
                'db_table': 'file_reminders',
                'verbose_name_plural': 'file_reminders',
            },
        ),
    ]
