# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_smstype'),
        ('employee', '0019_filereminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscaution',
            name='caution_type',
        ),
        migrations.AddField(
            model_name='filereminder',
            name='persian_date',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='phonefile',
            name='phone_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.PersonFile', verbose_name='نام شخص'),
        ),
        migrations.AddField(
            model_name='smscaution',
            name='mobile_number',
            field=models.CharField(default=None, max_length=12, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='smscaution',
            name='status',
            field=models.CharField(choices=[('در صف ارسال', 'در صف ارسال'), ('ارسال شد', 'ارسال شد'), ('دریافت شد', 'دریافت شد'), ('خطا در زمان ارسال', 'خطا در زمان ارسال')], default='در صف ارسال', max_length=100, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='smscaution',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.SmsType', verbose_name='نوع پیامک'),
        ),
    ]
