# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20180417_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'permissions': (('create_follow', 'create followup for file'), ('update_follow', 'update followup for file'), ('read_follow', 'read followup for file')), 'verbose_name': 'پیگیری کارشناس', 'verbose_name_plural': 'پیگیری کارشناسان'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('edit_profile', 'edit profile'),), 'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل کاربران'},
        ),
        migrations.AlterModelOptions(
            name='smscaution',
            options={'verbose_name': 'پیامک کارشناس', 'verbose_name_plural': 'پیامک کارشناسان'},
        ),
    ]
