# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_auto_20180220_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfile',
            options={'verbose_name': 'نوع وثایق', 'verbose_name_plural': 'نوع وثایق'},
        ),
        migrations.AlterModelOptions(
            name='employeefile',
            options={'verbose_name': 'تخصیص پرونده', 'verbose_name_plural': 'تخصیص پرونده'},
        ),
    ]
