# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_smstype'),
        ('employee', '0022_auto_20180220_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('recovery_type', models.CharField(choices=[('نقدی', 'نقدی'), ('چک', 'چک'), ('فروش رهنی', 'فروش رهنی')], default='نقدی', max_length=100, verbose_name='نوع وصولی')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='مبلغ وصولی')),
                ('value_code', models.CharField(default='0', max_length=200, verbose_name='شماره سند')),
                ('detail', models.TextField(verbose_name='شرح')),
                ('recovery_date', django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ')),
                ('created_at', django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='bank.File', verbose_name='پرونده')),
            ],
            options={
                'verbose_name_plural': 'file_recoveries',
                'db_table': 'file_recoveries',
                'verbose_name': 'file_recovery',
            },
        ),
    ]
