# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_filerecovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecovery',
            name='assurance_confirm',
            field=models.BooleanField(default=False, verbose_name='تاییدیه مالی'),
        ),
    ]
