# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_auto_20180511_1327'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0023_auto_20180510_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.ManagementAreas', verbose_name='area')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'access',
                'verbose_name_plural': 'access',
                'db_table': 'access',
            },
        ),
    ]
