# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_smstype'),
        ('employee', '0024_filerecovery_assurance_confirm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filerecovery',
            unique_together=set([('file', 'recovery_type', 'value_code')]),
        ),
    ]
