# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_accessemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessemployee',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_areas', to='bank.ManagementAreas', verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='accessemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
    ]
