# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_auto_20180518_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessemployee',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='accessemployee',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_areas', to='bank.ManagementAreas', verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='accessemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
