# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_auto_20180220_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscaution',
            name='mobile_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.PhoneFile', verbose_name='شماره تلفن'),
        ),
    ]
