# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0029_auto_20180221_0812'),
        ('employee', '0026_auto_20180221_0925'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smscaution',
            unique_together=set([('mobile_number', 'file', 'type')]),
        ),
    ]
