# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_auto_20180221_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscaution',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_cautions', to='bank.SmsType', verbose_name='نوع پیامک'),
        ),
    ]
