# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_auto_20180622_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_up_type',
            field=models.CharField(choices=[('call', 'تماس تلفنی'), ('meeting', 'مذاکره حضوری'), ('law', 'اقدامات قانونی'), ('other', 'سایر')], default='call', max_length=20, verbose_name='نوع پیگیری'),
        ),
    ]
