# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_auto_20180221_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='auth_status',
            field=models.CharField(choices=[('کارشناس', 'کارشناس'), ('وکیل', 'وکیل')], default='کارشناس', max_length=50, verbose_name='نوع تخصیص'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='status',
            field=models.CharField(choices=[('فعال', 'فعال'), ('غیرفعال', 'غیرفعال')], default='enable', max_length=50, verbose_name='وضعیت'),
        ),
    ]
