# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_auto_20180226_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefile',
            name='status',
            field=models.CharField(choices=[('enable', 'فعال'), ('disable', 'غیر فعال')], default='enable', max_length=50, verbose_name='وضعیت'),
        ),
    ]
