# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 10:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0030_branch_code'),
        ('employee', '0032_auto_20180301_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeefile',
            unique_together=set([('file', 'employee')]),
        ),
    ]
