# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('count_file', models.PositiveIntegerField(default=0, verbose_name='تعداد کل پرونده')),
                ('value_file', models.PositiveIntegerField(default=0, verbose_name='مبلغ کل پرونده')),
                ('count_file_daily', models.PositiveIntegerField(default=0, verbose_name='تعداد پرونده های ارجاعی')),
                ('value_file_daily', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرونده های ارجاعی')),
                ('count_file_recovery', models.PositiveIntegerField(default=0, verbose_name='تعداد پرونده های تسویه')),
                ('value_file_recovery', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرونده های تسویه')),
                ('value_recovery', models.PositiveIntegerField(default=0, verbose_name='مبلغ کل وصولی روز')),
                ('count_file_peygiri', models.PositiveIntegerField(default=0, verbose_name='تعداد پیگیری های روز')),
                ('persian_date', django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='پرسنل')),
            ],
            options={
                'db_table': 'persons_daily_report',
                'verbose_name': 'person_daily_report',
                'verbose_name_plural': 'persons_daily_report',
            },
        ),
        migrations.AlterUniqueTogether(
            name='persondailyreport',
            unique_together=set([('user', 'persian_date')]),
        ),
    ]
