# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersonDailyReport',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('update_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated date')),
                ('count_file', models.PositiveIntegerField(default=0, verbose_name='تعداد کل پرونده')),
                ('value_file', models.PositiveIntegerField(default=0, verbose_name='مبلغ کل پرونده')),
                ('count_file_daily', models.PositiveIntegerField(default=0, verbose_name='تعداد پرونده های ارجاعی')),
                ('value_file_daily', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرونده های ارجاعی')),
                ('count_file_recovery', models.PositiveIntegerField(default=0, verbose_name='تعداد پرونده های تسویه')),
                ('value_file_recovery', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرونده های تسویه')),
                ('value_recovery', models.PositiveIntegerField(default=0, verbose_name='مبلغ کل وصولی روز')),
                ('count_file_peygiri', models.PositiveIntegerField(default=0, verbose_name='تعداد پیگیری های روز')),
                ('persian_date', django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical person_daily_report',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
