# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 22:13
from __future__ import unicode_literals

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20180215_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondailyreport',
            name='persian_date',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ'),
        ),
    ]
