# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_dailyweather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyWeather',
        ),
    ]
