# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_delete_dailyweather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondailyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='پرسنل'),
        ),
    ]
